name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install requirements
      run: pip3 install -r requirements.txt
    - name: test
      run: python3 manage.py test > stdout.txt 2> stderr.txt
    - name: test fails
      if: failure()
      run: |
        line=$(head -n 2 stderr.txt )
        curl -d "username=${{ github.actor }}&repo=${{ github.repository }}&test=$line" -X POST https://warehouse-api.joincoded.com/github/task/pushed/python/
    - name: test
      run: python3 manage.py test 
    - name: test passes
      if: success()
      run: curl -d "username=${{ github.actor }}&repo=${{ github.repository }}&test=." -X POST https://warehouse-api.joincoded.com/github/task/pushed/python/
